### PR TITLE
Homepage layout and styles

### PR DESCRIPTION
**Pull request by joshangehr**
I've added the template for the homepage along with it's corresponding styles. I've used SCSS in a few places for variables and colour modules, but can easily scale back and integrate differently if this interrupts anyone's workflow. Happy to present for a second set of eyes.

### CODE REVIEW

**Comment by KTS915** [comment]
Please could you use just plain CSS and not SCSS. In accordance with our stated aim of CP's being a community project, this really does need to be as open as possible to editing by different people. Consistency is also vital; otherwise, we will have everybody doing their own thing -- and things could get messy very quickly.

**Comment by striebwj** [comment]
@KTS915 I am going to swap it to CSS, but for now I have merged this PR.

Thanks @joshangehr for getting the home page done!

**Comment by KTS915** [comment]
Thanks, @striebwj!

**Comment by joshangehr** [comment]
Sure thing, but I recommend setting up a development workflow at some point. Plain CSS will become impossible to manage in the future. Sass variables force design consistency and minimize code, and pave the road for a manageable and maintainable design system.

@striebwj No problem 😄

**Comment by senlin** [comment]
Is the `template-home.php` just dummy content  or will it be used in some way or other? In that case can we please internationalise the strings?

**Comment by joshangehr** [comment]
@senlin I assumed it was all dummy content that would be replaced via custom meta fields or hardcoded text.

**Comment by KTS915** [comment]
This theme should never get to the stage where CSS will become impossible to manage. That's part of the point of choosing the Susty theme as a base. If we end up with a huge amount of CSS, then we will be doing it wrong.

**Comment by striebwj** [comment]
I merged the two stylesheets into one, so we are all good now, with just CSS.

**Comment by nylen** [comment]
> Sure thing, but I recommend setting up a development workflow at some point. Plain CSS will become impossible to manage in the future. Sass variables force design consistency and minimize code, and pave the road for a manageable and maintainable design system.

This is true, but SASS also adds a build step.  Build steps have a way of getting out of hand pretty quickly.

We also discussed this previously in https://github.com/ClassicPress/ClassicPress-Themes/issues/2.

If a build step is added in the future, it needs to be well-tested on at least OS X and Linux, and clearly documented.

**Pull request merged**
